### ISSUE TITLE
Feature Request: Add custom Icons

### ISSUE THREAD

**Issue by BRod79** [zombieFox/nightTab#100]
Custom icons would have been great.  Letters are ok, but a custom uploader or folder to add your own, would be sweet.

**Comment by zombieFox** [comment]
I'm afraid this is out of scope of this project, since nightTab is a local project, running on the browser without accounts or databases to store date like that. Also because the upload [background image](https://github.com/zombieFox/nightTab/blob/master/src/js/background.js#L85) feature can be local storage intensive (others have also [reported](https://github.com/zombieFox/nightTab/issues/69) even this can be unpredictable).

It's also difficult to treat images the same as the icons/letters over the bookmark tiles. So I'm not planing to support custom uploading of images.
