### ISSUE TITLE
Addon ignores specified query strings in search url

### ISSUE THREAD

**Issue by ilya-fedin** [zombieFox/nightTab#103]
I specified `https://yandex.ru/search/?text=`, but addon uses `https://yandex.ru/search/?q=`

**Comment by zombieFox** [comment]
I'll look into this.

**Comment by zombieFox** [comment]
Tried to investigate this futher but I'm having no luck. Especially since I can't get past this captcha test during my experiments. Some search engines just won't work with this project. 

<img width="401" alt="Screenshot 2020-06-10 at 12 40 25" src="https://user-images.githubusercontent.com/7115017/84263629-bc4d4700-ab17-11ea-91bd-253c275a2965.png">
(It's especially difficult since some of the words it shows me have Russian letters which I can't type out)

Sorry, closing as I can't do more.

**Comment by ilya-fedin** [comment]
> Tried to investigate this futher but I'm having no luck.

The problem is that the input has staic `name="q"`. An option to change that or getting the content from the input with and going to the url + text in input would fix the issue.

**Comment by zombieFox** [comment]
This feature is now on live 👍
