### ISSUE TITLE
[Bug] Edit/Add and Colour/Accent sizes reset to default on page refresh

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#154]
The settings menu does reflect the value of 60 but the buttons render at 100. Very similar to Issue #70.

**Comment by zombieFox** [comment]
I know exactly what this bug is and when it was introduced (by me 🙈 ). It's a missing call to a [size function on page load here](https://github.com/zombieFox/nightTab/blob/master/src/js/header.js#L532). Thanks for letting me know.  I've pushed a [fix](https://github.com/zombieFox/nightTab/commit/9ef8732a1bfea447da8859c4f0ef900cf5dcf58b). Will be live in the next update shortly.
