### ISSUE TITLE
About Opera

### ISSUE THREAD

**Issue by TOLIN987** [zombieFox/nightTab#176]
They could add nighthub as an extension for Opera. In order to have it in my default browser.

**Comment by Excigma** [comment]
Can you get it from the Chrome web store?
Link: https://chrome.google.com/webstore/detail/nighttab/hdpcadigjkbcpnlcpbcohpafiaefanki

**Comment by TOLIN987** [comment]
I tried previously but the extension does not work, even after having restarted the browser it still did not work. So if you added it I would appreciate it

**Comment by zombieFox** [comment]
I don't know how Opera handles extensions. I'll look into what @Excigma mentioned. 

As far as the scope of the project, I only ever intended nightTab to support Chrome and Firefox because they both use the same [manifest.json](https://github.com/zombieFox/nightTab/blob/master/src/manifest.json) set up. So if Opera does the same it should just work. I'll investigate.

**Comment by TOLIN987** [comment]
OK thanks. I hope it is something similar to chrome and firefox, so that I can use it.

**Comment by zombieFox** [comment]
Looks like Opera no longer supports replacing the new tab page. This is a decsison made by Opera and publishing an extension which does so will not pass moderation:

> Extensions cannot replace Opera’s default start page.

https://dev.opera.com/extensions/acceptance-criteria/

https://stackoverflow.com/questions/44635013/why-in-opera-the-chrome-url-overrides-is-not-allowed-for-specified-extension-i

That's a shame. Closing this issue as I can't devote more time to this.
