### ISSUE TITLE
load time is ~3+ seconds. Why? the extension and all the files are saved locally. Please fix.

### ISSUE THREAD

**Issue by KraXen72** [zombieFox/nightTab#211]
this was one of the faster times but sometimes i get like 5 seconds load and it's annoying..
please fix, thanks.
you could maybe  just like load the link tiles first, not covered by the splash screen so if i quickly want to click it it's available, and load the other css like bg image and stuff gradually.
![Rec_2020_05 09_10;30](https://user-images.githubusercontent.com/21956756/92301299-e66da400-ef62-11ea-959d-17ece3e77843.gif)

**Comment by KraXen72** [comment]
HexagonTab is way faster

**Comment by zombieFox** [comment]
Thanks for the feedback @KraXen72 

I can see this is similar to another issue, please see #185 for a bit more information.

In short loading times are depended on the system load, browser cache, background image load times and a load of other factors. Improvements are an ongoing process and there is no quick fix for something which is quite complex.

hexagonTab is faster because it has been built in a completely different way to nightTab, (I have learnt a lot in the two years since I made nightTab) and is a smaller project since it has much fewer features. So the browser has less code to parse and load.

In theory I could rebuild nightTab in a similar way as hexagonTab but that would be months and months of time.

**Comment by Zbergen-cli** [comment]
Hey. I am seeing the same problem. My settings:
10 sites I visit frequently as tiles
Changed background
Changed font color for tiles
Changed color when hovering over a tile

As you can see, the page is set up minimalist, but it takes a long time to load. I am using latest Firefox and latest nightTab. My computer has a core i5 and 8GB of RAM.

**Comment by KraXen72** [comment]
i have solved this problem by taking a screenshot of every tile and using the default vivaldi start page. it only looks 90% as good as nighttab and if i wanted to add a new tab, i'd have to take a screenshot from night tab, but it loads instantly. and by instantly i mean litteraly instantly. 
this is how it looks:
![image](https://user-images.githubusercontent.com/21956756/95653345-6524a680-0af8-11eb-906d-6efa2b89b09b.png)
