### ISSUE TITLE
Store of presets online.

### ISSUE THREAD

**Issue by Sparklytical** [zombieFox/nightTab#225]
It will be great if there can be some sort of preset website or just an issue where users can post their presets alongside the images.

**Comment by Q-out** [comment]
I agree, a collection of presets would enhance experience by a lot, and you could even link to it from inside the extension. But currently "presets" would overwrite your bookmarks and you'd have to add them all back one by one... which is why I submitted request #163 a while ago.
But for new users it'd be useful even as it is right now. Your #226 works well I think.

**Comment by zombieFox** [comment]
A new set of import controls are out in v7 release. This should help with issues raised here and in #163. The work continues 💻 

We also have a new subreddit to share presets over on [reddit.com/r/nighttab](https://www.reddit.com/r/nighttab/)

**Comment by zombieFox** [comment]
We now have a [reddit community](https://www.reddit.com/r/nighttab/) and a [GitHub Discussion](https://github.com/zombieFox/nightTab/discussions/275) set up to share set ups. 

Closing this issue 🎸
