### ISSUE TITLE
Where to access nighttab.min.js

### ISSUE THREAD

**Issue by Lalit64** [zombieFox/nightTab#260]
Where do we access the nighttab.min.js. and how do we change it?

**Comment by zombieFox** [comment]
Hi, there is no nightTab.min.js file. What are you hoping to do?

**Comment by Lalit64** [comment]
I wanna add a custom favicon using <code>(function() {
var link = document.querySelector("link[rel*='icon']") || document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = 'chrome://branding/content/icon32.png';
    document.getElementsByTagName('head')[0].appendChild(link);
})();</code> and i was told to put it in the nighttab.min.js

**Comment by Lalit64** [comment]
@zombieFox I realized that with the new version you added a favicon and I wanted to know if you could add a feature to allow customization of this favicon?

**Comment by zombieFox** [comment]
> @zombieFox I realized that with the new version you added a favicon and I wanted to know if you could add a feature to allow customization of this favicon?

Hi @Lalit64 This is correct, but there are some additional details for context. Chrome did previously prevent extensions from adding a favicon to new tab pages. Please see the discussion on [issue 110](https://github.com/zombieFox/nightTab/issues/110) for details of this investigation. Looks like a recent Chrome update has changed this and now is showing the Favicon. So adding controls to change this should be possible -- but will need some time to develop and test.

I'll tag this as a feature request for now. Please also not that new feature requests [are on hold](https://github.com/zombieFox/nightTab/issues/255) so that I can focus on optimisation improvements.

**Comment by Lalit64** [comment]
Would it be possible if we use tampermonkey and use the us code I sent with whatever favocon?

**Comment by zombieFox** [comment]
Sorry, I don't know what tampermonkey can do with a new tab page. 

I've [added controls](https://github.com/zombieFox/nightTab/commit/e3dbf21e5ef7d392eecababf5961b5f230e73f51) to change the `link` tag `href` -- to change the favicon. It should work but can't be guaranteed to work in all browsers. Should be included in the next release.

**Comment by Lalit64** [comment]
> Sorry, I don't know what tampermonkey can do with a new tab page. 
> 
> 
> 
> I've [added controls](https://github.com/zombieFox/nightTab/commit/e3dbf21e5ef7d392eecababf5961b5f230e73f51) to change the `link` tag `href` -- to change the favicon. It should work but can't be guaranteed to work in all browsers. Should be included in the next release. 
> 
> 

Ok so when does the next release come out?

**Comment by zombieFox** [comment]
The recent [7.x update](https://github.com/zombieFox/nightTab/releases/tag/v7.3.0) is now out and has a favicon control. This is not supported in every browser but does work in Firefox and Chrome in my tests. Marking this as complete.
