### ISSUE TITLE
unable to create bookmark

### ISSUE THREAD

**Issue by gnarlyCrone** [zombieFox/nightTab#282]
I am unable to create a new bookmark but I am able to create a new group.

I started using nightTab today and have set up 4 groups and 9 bookmarks without issue. However, I am unable to create the tenth bookmark. Clicking on the + simply changes colour to indicate I have clicked but nothing else happens.

I am using Chrome Version 93.0.4577.82 (Official Build) (64-bit) and the  Windows 10 21H1

I recorded my screen and what happens.
https://user-images.githubusercontent.com/50375305/133348977-1ef7d6c9-b8c5-4e70-b634-cb0a508695d7.mp4

I have also exported data to see if that helps you narrow down the problem. (I added .txt to the file so I could upload it)
[nightTab backup - 2021.09.14 - 16 59 22.json .txt](https://github.com/zombieFox/nightTab/files/7165770/nightTab.backup.-.2021.09.14.-.16.59.22.json.txt)

I will have to disable this as I can't finish adding the items I want.

I have tried rebooting but it didn't help.

**Comment by zombieFox** [comment]
Hi @gnarlyCrone, Sorry you experiencing this issue. I've had a look at the video and backup JSON. It seems you have indeed found a bug! 🐞 

The cause seems to be some special characters in the Group names. In this instance it's the commas `,` in  "Financial, Business, Communication". I've [made a fix](https://github.com/zombieFox/nightTab/commit/a6f088c2c77c82c2421df0dbb797e60950d88390) which will be published to Chrome in a week or two (Chrome takes a long time to approve extensions).

In the interim you can remove the commas from your group names until the fix is live. Again, apologies you got hit with this bug.

**Comment by gnarlyCrone** [comment]
Thank you for the quick response.

**Comment by Laviine** [comment]
Is it out now? I'm sorry but I am also getting this bug and it's a little annoying that I can't add any bookmarks at the moment. Thanks.

**Comment by zombieFox** [comment]
Yes, an update is out -- you can update to 7.3.0 on both Firefox and Chrome.
