### ISSUE TITLE
Video Wallpaper Not working

### ISSUE THREAD

**Issue by Narimanghods** [zombieFox/nightTab#296]
Hi,

This is the second time i'm reaching out to fix my issue. I received a response last time but then my message was deleted.

I am trying to set my background as a video, however it does not work. I have followed the instructions yet it still does not seem to function properly. 

 - OS: MacOS
 - Browser: Google Chrome Version 94.0.4606.71 (Official Build) (x86_64)
 - nightTab version: 7.0.2

Thanks.

**Comment by zombieFox** [comment]
Hi again, your issue was not deleted, it [was closed](https://github.com/zombieFox/nightTab/issues/295). The issue you have is that the URL you are using is a webpage. You need to link directly to a MP4 file. The [wiki page](https://github.com/zombieFox/nightTab/wiki/Setting-a-background-video-or-image#background-video) on video backgrounds has an example URL to show the difference: `https://github.com/zombieFox/nightTabAssets/blob/main/videos/1626342620002.mp4?raw=true`

**Comment by Narimanghods** [comment]
How do I post a video as you did on github?

**Comment by Narimanghods** [comment]
Thank you :)

**Comment by zombieFox** [comment]
Welcome! Closing this one too.
