### ISSUE TITLE
Stackable Bookmarks

### ISSUE THREAD

**Issue by HalalJadeja** [zombieFox/nightTab#333]
Hey guys, I've come to know about nightTab from no-text-to-speech, who is a YouTuber, he added a few themes and I am trying to use one and modify it a bit. I've seen a few things I would suggest:

1. Please decrease the extra space taken by the clock - ( check this image) https://media.discordapp.net/attachments/859323882805002250/928543464877097000/unknown.png?width=842&height=473

2. Please enable the stacking option, we are unable to put a normal bookmark beneath a wide one. ( check this image ) https://media.discordapp.net/attachments/859323882805002250/928543792951357450/unknown.png?width=842&height=473
Thanks!

**Comment by zombieFox** [comment]
Hi. I'll try and help.

1. The clock looks like it is taking the whole row because it is set to `New Line` which forces the element to take full width. This can be changed under `Settings menu` (gear icon) > `Header` > `Clock` > `New line`.

2. The project uses a [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) with auto flow columns and rows. So bookmark tiles start top left and flow to the right. When tall or wide bookmark tiles are used some may not have space to fit in. You should be able to change the width of the layout or bookmark area to get the desired bookmark positions. As seen here:


https://user-images.githubusercontent.com/7115017/148546344-ff6e5108-3cde-4323-9570-ff2651932856.mp4
