### ISSUE TITLE
request: wallpaper list randomizer

### ISSUE THREAD

**Issue by ronmurphy** [zombieFox/nightTab#85]
Is it possible to have a text box where we can add in a link to a wallpaper, and it adds it to a list where we can also choose to delete a wallpaper (click link to highlight / set focus/index?) then a button to delete that selected url?  

Have an option that on page shown, it will pick a url at random (or as close as random can be...) and set that image as the background.  if this option is not checked/ticked, it will just keep on using the default, not random wallpaper.

IDK if i explained this the correct way, i want to say 'this seems easy enough to do', but that's never the case, really.  It's just an idea is all.  I showed off nightTab to several friends and all of them asked if it had a wallpaper randomizer built in... I had to say no, so I thought I would go do a request for it.  Thanks!

**Comment by zombieFox** [comment]
Thanks for the feedback. I'm sorry I am having trouble understanding this request. Essentially, are you asking for random wallpapers on load? 

I can look into this. But it if it were to become a feature it would be based on URLs and not locally stored files. The local file image background feature is already experiencing issues [due to file sizes](https://github.com/zombieFox/nightTab/issues/69). I'll investigate. 

In the mean time you could use the Unsplash random URL to achieve what I think you may be asking for. Try using this URL in the "Use URL" field: `https://source.unsplash.com/random/1920x1080/?night,day,sky`. 

Changing the words after the `?` lets you narrow down the images.

**Comment by jmanpenilla** [comment]
I've created a really basic implementation. Let me know what you think of this #89

**Comment by zombieFox** [comment]
Feature is now live 🔥

**Comment by ronmurphy** [comment]
nice, thank you!
